### ISSUE TITLE
How would you get this to take in an OccupancyGrid

### ISSUE THREAD

**Issue by vinnnyr** [gKouros/reeds-shepp-paths-ros#1]
Hello,

I was wondering if you had any suggestions on how you would change the demo to take in an OccupancyGrid  as hosted by the [map server](http://wiki.ros.org/map_server)?

I appreciate your help.

Best,
Vinny

**Comment by gkouros** [comment]
Maybe this project could be useful https://github.com/gkouros/rsband_local_planner

**Comment by vinnnyr** [comment]
Mainly I am looking to use this as a Global Planner.

**Comment by gkouros** [comment]
I'm not sure if it's possible to integrate the OMPL reeds-shepp state space library with an OGM. What I would do would be to extend the global_planner plugin with a reeds-shepp path deformation algorithm. So, you can create a new global planner plugin (eg. rs_global_planner) in which you first construct an optimal holonomic global path using A* or Dijkstra and then you make it feasible for car-like robots using reeds-shepp planning between waypoints or from start to end. For the second part you can reuse part of my code in rsband_local_planner repo. Hope that helps.
